export const UTIL = {
    SET_PAGE_TAB: "UTIL::SET_PAGE_TAB",
    SET_ERROR: "UTIL::SET_ERROR",
    UNSET_ERROR: "UTIL::UNSET_ERROR",
    SET_SELLER_METADATA: "UTIL::SET_SELLER_METADATA",
    SET_FULLSCREEN_LOADER: "UTIL::SET_FULLSCREEN_LOADER",
    UNSET_FULLSCREEN_LOADER: "UTIL::UNSET_FULLSCREEN_LOADER",
    SET_IS_LOGGED_IN: "UTIL::SET_IS_LOGGED_IN", 
  };

export const CONTACT = {
  GET_ALL_CONTACTS: "CONTACT::GET_ALL_CONTACTS",
}